/**
 **********************************************************************
 * Copyright (c) 1988-2008 $author$
 *
 * This software is provided by the author and contributors ``as is'' 
 * and any express or implied warranties, including, but not limited to, 
 * the implied warranties of merchantability and fitness for a particular 
 * purpose are disclaimed. In no event shall the author or contributors 
 * be liable for any direct, indirect, incidental, special, exemplary, 
 * or consequential damages (including, but not limited to, procurement 
 * of substitute goods or services; loss of use, data, or profits; or 
 * business interruption) however caused and on any theory of liability, 
 * whether in contract, strict liability, or tort (including negligence 
 * or otherwise) arising in any way out of the use of this software, 
 * even if advised of the possibility of such damage.
 *
 *   File: caclexer.hxx
 *
 * Author: $author$
 *   Date: 7/30/2008
 **********************************************************************
 */
#ifndef _CACLEXER_HXX
#define _CACLEXER_HXX

#include "cacparse.hxx"
#include "clexerdelegate.hxx"
#include "clexer.hxx"

#undef yyIsLexer
#undef yyLexer
#undef cYYIsLexer
#define yyIsLexer cACIsLexer
#define yyLexer cACLexer
#define cYYIsLexer cACLexerExtends
#include "cyylexer.hxx"

/**
 **********************************************************************
 *  Class: cACLexerDelegate
 *
 * Author: $author$
 *   Date: 7/30/2008
 **********************************************************************
 */
class cACLexerDelegate
: public cLexerDelegateT<cACLexerDelegate>
{
public:
    typedef cLexerDelegateT<cACLexerDelegate> cExtends;
    typedef cACLexerDelegate cDelegate;
};

/**
 **********************************************************************
 *  Class: cACLexer
 *
 * Author: $author$
 *   Date: 7/30/2008
 **********************************************************************
 */
class cACLexer
: public cLexerT
  <cACLexerDelegate,cACLexerExtends,
   cLexerSource,cCharStreamInterface>
{
public:
    typedef cLexerT
    <cACLexerDelegate,cACLexerExtends,
     cLexerSource,cCharStreamInterface> cExtends;
    typedef cACLexer cDerives;

    /**
     **********************************************************************
     * Constructor: cACLexer
     *
     *      Author: $author$
     *        Date: 7/30/2008
     **********************************************************************
     */
    cACLexer
    (cACLexerDelegate& delegate,
     cCharStreamInterface& out, 
     cCharStreamInterface& in, 
     cLexerSource &source)
    : cExtends(delegate, out, in, source) 
    {
    }
    /**
     **********************************************************************
     * Function: OnIdentifierToken
     *
     *   Author: $author$
     *     Date: 7/30/2008
     **********************************************************************
     */
    virtual eError OnIdentifierToken
    (const char* text, int token=-1,
     int beginchars=0, int endchars=0) 
    {
        eError error = e_ERROR_NONE;
        cDelegate* m_delegate;
        if ((m_delegate = GetDelegate()))
            error = m_delegate->OnIdentifierToken
            (text, token, beginchars, endchars);
        OnUpperTokenText
        (text, token, beginchars, endchars);
        return error;
    }
    /**
     **********************************************************************
     * Function: yylex
     *
     *   Author: $author$
     *     Date: 7/30/2008
     *
     * This function is generated by flex.
     **********************************************************************
     */
	virtual int yylex();
};

#endif /* _CACLEXER_HXX */
