///////////////////////////////////////////////////////////////////////
//   File: evcpheaderfield.h
//
// Author: $author$
//   Date: 5/18/2007
//
//    $Id$
///////////////////////////////////////////////////////////////////////

#ifndef _EVCPHEADERFIELD_H
#define _EVCPHEADERFIELD_H

#include "evhttpheaderfield.h"

#define EVCP_HEADER_FIELD_SEPARATOR \
    EVHTTP_HEADER_FIELD_SEPARATOR

#define EVCP_HEADER_FIELD_NAME_SEPARATOR \
    EVHTTP_HEADER_FIELD_NAME_SEPARATOR

#define EVCP_HEADER_FIELD_NAME_CONTENT_TYPE \
    EVHTTP_HEADER_FIELD_NAME_CONTENT_TYPE

#define EVCP_HEADER_FIELD_NAME_CONTENT_LENGTH \
    EVHTTP_HEADER_FIELD_NAME_CONTENT_LENGTH

#define EVCP_HEADER_FIELD_NAME_CONTENT_ENCODING \
    EVHTTP_HEADER_FIELD_NAME_CONTENT_ENCODING

#define EVCP_HEADER_FIELD_NAME_TRANSFER_ENCODING \
    EVHTTP_HEADER_FIELD_NAME_TRANSFER_ENCODING

#define EVCP_HEADER_FIELD_NAME_ENCODING_IDENTITY \
    EVHTTP_HEADER_FIELD_NAME_ENCODING_IDENTITY

#define EVCP_HEADER_FIELD_NAME_ENCODING_HEX \
    EVHTTP_HEADER_FIELD_NAME_ENCODING_HEX

#define EVCP_HEADER_FIELD_NAME_ENCODING_BASE64 \
    EVHTTP_HEADER_FIELD_NAME_ENCODING_BASE64

#define EVCP_HEADER_FIELD_NAME_ENCODING_EVCPS "evcps"

#define EVCP_HEADER_FIELD_NAME_USER "User"
#define EVCP_HEADER_FIELD_NAME_CREDENTIALS "Credentials"
#define EVCP_HEADER_FIELD_NAME_PASSWORD "Password"

#define EVCP_HEADER_FIELD_NAME_ACTION "Action"
#define EVCP_HEADER_FIELD_NAME_METHOD "Method"

#define EVCP_HEADER_FIELD_NAME_CONTROL "Control"
#define EVCP_HEADER_FIELD_NAME_LOCAL "Local"
#define EVCP_HEADER_FIELD_NAME_PATH "Path"

#define EVCP_HEADER_FIELD_NAME_CONTROL_PATH \
    EVCP_HEADER_FIELD_NAME_CONTROL \
    EVCP_HEADER_FIELD_NAME_SEPARATOR \
    EVCP_HEADER_FIELD_NAME_PATH

#define EVCP_HEADER_FIELD_NAME_LOCAL_PATH \
    EVCP_HEADER_FIELD_NAME_LOCAL \
    EVCP_HEADER_FIELD_NAME_SEPARATOR \
    EVCP_HEADER_FIELD_NAME_PATH

#define EVCP_HEADER_FIELD_NAME_TIME "Time"

#define EVCP_HEADER_FIELD_NAME_TIME_ \
    EVCP_HEADER_FIELD_NAME_TIME \
    EVCP_HEADER_FIELD_NAME_SEPARATOR

#define EVCP_HEADER_FIELD_NAME_BLOCK "Block"
#define EVCP_HEADER_FIELD_NAME_BLOCK_SIZE "Block-Size"
#define EVCP_HEADER_FIELD_NAME_BLOCK_LENGTH "Block-Length"

#define EVCP_HEADER_FIELD_NAME_CONNECTION "Connection"
#define EVCP_HEADER_FIELD_VALUE_CONNECTION_KEEPALIVE "Keep-Alive"
#define EVCP_HEADER_FIELD_VALUE_CONNECTION_CLOSE "Close"

#define EVCP_HEADER_FIELD_NAME_IS_BINARY "Is-Binary"
#define EVCP_HEADER_FIELD_VALUE_IS_BINARY_NO "No"
#define EVCP_HEADER_FIELD_VALUE_IS_BINARY_YES "Yes"

#define EVCP_HEADER_FIELD_NAME_IS_RECURSIVE "Is-Recursive"
#define EVCP_HEADER_FIELD_VALUE_NO "No"
#define EVCP_HEADER_FIELD_VALUE_YES "Yes"

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
}
#endif

#endif // _EVCPHEADERFIELD_H
