///////////////////////////////////////////////////////////////////////
//   File: evcprequest.h
//
// Author: $author$
//   Date: 5/14/2007
//
//    $Id$
///////////////////////////////////////////////////////////////////////

#ifndef _EVCPREQUEST_H
#define _EVCPREQUEST_H

#define EVCP_REQUEST_PATH_SEPARATOR '/'
#define EVCP_REQUEST_PATH_SEPARATOR_STRING "" EVCP_REQUEST_PATH_SEPARATOR ""
#define EVCP_REQUEST_PATH_ROOT EVCP_REQUEST_PATH_SEPARATOR_STRING

///////////////////////////////////////////////////////////////////////
//   Enum:  
//
// Author: $author$
//   Date: 5/14/2007
///////////////////////////////////////////////////////////////////////
typedef enum 
{
    EVCP_FIRST_REQUEST_ACTION,

    EVCP_REQUEST_ACTION_CI = EVCP_FIRST_REQUEST_ACTION,
    EVCP_REQUEST_ACTION_CO,
    EVCP_REQUEST_ACTION_DO,
    EVCP_REQUEST_ACTION_STOP,
    EVCP_REQUEST_ACTION_RESTART,
    EVCP_REQUEST_ACTION_HELLO,

    EVCP_NEXT_REQUEST_ACTION,
    EVCP_LAST_REQUEST_ACTION = EVCP_NEXT_REQUEST_ACTION-1,

    EVCP_REQUEST_ACTIONS = EVCP_NEXT_REQUEST_ACTION
}  ;

#define EVCP_REQUEST_ACTION_NAME_EVCPS "EVCPS"

#define EVCP_REQUEST_ACTION_NAME_LOGIN "LOGIN"
#define EVCP_REQUEST_ACTION_NAME_LOGOUT "LOGOUT"

#define EVCP_REQUEST_ACTION_NAME_GET "GET"
#define EVCP_REQUEST_ACTION_NAME_PUT "PUT"

#define EVCP_REQUEST_ACTION_NAME_CI "CI"
#define EVCP_REQUEST_ACTION_NAME_CO "CO"

#define EVCP_REQUEST_ACTION_NAME_LOCK "LOCK"
#define EVCP_REQUEST_ACTION_NAME_UNLOCK "UNLOCK"

#define EVCP_REQUEST_ACTION_NAME_DO "DO"

#define EVCP_REQUEST_ACTION_NAME_STATUS "STATUS"

#define EVCP_REQUEST_ACTION_NAME_START "START"
#define EVCP_REQUEST_ACTION_NAME_STOP "STOP"
#define EVCP_REQUEST_ACTION_NAME_RESTART "RESTART"

#define EVCP_REQUEST_ACTION_NAME_FINISH "FINISH"
#define EVCP_REQUEST_ACTION_NAME_CANCEL "CANCEL"

#define EVCP_REQUEST_ACTION_NAME_BREAK "BREAK"
#define EVCP_REQUEST_ACTION_NAME_CONTINUE "CONTINUE"

#define EVCP_REQUEST_ACTION_NAME_BEGIN "BEGIN"
#define EVCP_REQUEST_ACTION_NAME_END "END"

#define EVCP_REQUEST_ACTION_NAME_HELLO "HELLO"

#define EVCP_REQUEST_ACTION_ARGUMENT_NAME_BEGIN EVCP_REQUEST_ACTION_NAME_BEGIN
#define EVCP_REQUEST_ACTION_ARGUMENT_NAME_END EVCP_REQUEST_ACTION_NAME_END

#define EVCP_REQUEST_ACTION_ARGUMENT_NAME_CANCEL EVCP_REQUEST_ACTION_NAME_CANCEL

#define EVCP_REQUEST_ACTION_ARGUMENT_NAME_NOW "NOW"

#if defined(__cplusplus)
extern "C" {
#endif

extern int g_evcpRequestActionValue[EVCP_REQUEST_ACTIONS];
extern const char* g_evcpRequestActionName[EVCP_REQUEST_ACTIONS];

#if defined(__cplusplus)
}
#endif

#endif // _EVCPREQUEST_H
