///////////////////////////////////////////////////////////////////////
//   File: evhttpheaderfield.h
//
// Author: $author$
//   Date: 8/14/2007
//
//    $Id$
///////////////////////////////////////////////////////////////////////

#ifndef _EVHTTPHEADERFIELD_H
#define _EVHTTPHEADERFIELD_H

#define EVHTTP_HEADER_FIELD_SEPARATOR ':'
#define EVHTTP_HEADER_FIELD_NAME_SEPARATOR "-"
#define EVHTTP_HEADER_FIELD_VALUE_SEPARATOR "-"

#define EVHTTP_HEADER_FIELD_NAME_CONTENT "Content"
#define EVHTTP_HEADER_FIELD_NAME_TRANSFER "Transfer"

#define EVHTTP_HEADER_FIELD_NAME_LENGTH "Length"
#define EVHTTP_HEADER_FIELD_NAME_TYPE "Type"
#define EVHTTP_HEADER_FIELD_NAME_ENCODING "Encoding"

#define EVHTTP_HEADER_FIELD_NAME_ENCODING_CHUNKED "chunked"
#define EVHTTP_HEADER_FIELD_NAME_ENCODING_COMPRESS "compress"
#define EVHTTP_HEADER_FIELD_NAME_ENCODING_DEFLATE "deflate"
#define EVHTTP_HEADER_FIELD_NAME_ENCODING_GZIP "gzip"
#define EVHTTP_HEADER_FIELD_NAME_ENCODING_IDENTITY "identity"

#define EVHTTP_HEADER_FIELD_NAME_ENCODING_7BIT "7bit"
#define EVHTTP_HEADER_FIELD_NAME_ENCODING_8BIT "8bit"
#define EVHTTP_HEADER_FIELD_NAME_ENCODING_BINARY "binary"
#define EVHTTP_HEADER_FIELD_NAME_ENCODING_BASE64 "base64"
#define EVHTTP_HEADER_FIELD_NAME_ENCODING_OCTAL "octal"
#define EVHTTP_HEADER_FIELD_NAME_ENCODING_HEX "hex"

#define EVHTTP_HEADER_FIELD_NAME_CONTENT_LENGTH \
    EVHTTP_HEADER_FIELD_NAME_CONTENT \
    EVHTTP_HEADER_FIELD_NAME_SEPARATOR \
    EVHTTP_HEADER_FIELD_NAME_LENGTH

#define EVHTTP_HEADER_FIELD_NAME_CONTENT_TYPE \
    EVHTTP_HEADER_FIELD_NAME_CONTENT \
    EVHTTP_HEADER_FIELD_NAME_SEPARATOR \
    EVHTTP_HEADER_FIELD_NAME_TYPE

#define EVHTTP_HEADER_FIELD_NAME_CONTENT_ENCODING \
    EVHTTP_HEADER_FIELD_NAME_CONTENT \
    EVHTTP_HEADER_FIELD_NAME_SEPARATOR \
    EVHTTP_HEADER_FIELD_NAME_ENCODING

#define EVHTTP_HEADER_FIELD_NAME_TRANSFER_ENCODING \
    EVHTTP_HEADER_FIELD_NAME_TRANSFER \
    EVHTTP_HEADER_FIELD_NAME_SEPARATOR \
    EVHTTP_HEADER_FIELD_NAME_ENCODING

#define EVHTTP_HEADER_FIELD_VALUE_KEEP "Keep"
#define EVHTTP_HEADER_FIELD_VALUE_ALIVE "Alive"
#define EVHTTP_HEADER_FIELD_VALUE_CLOSE "Close"

#define EVHTTP_HEADER_FIELD_VALUE_KEEP_ALIVE \
    EVHTTP_HEADER_FIELD_VALUE_KEEP \
    EVHTTP_HEADER_FIELD_VALUE_SEPARATOR \
    EVHTTP_HEADER_FIELD_VALUE_ALIVE

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
}
#endif

#endif // _EVHTTPHEADERFIELD_H
