#!/bin/bash
########################################################################
# Copyright (c) 1988-2021 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: evup
#
# Author: $author$
#   Date: 3/31/2021, 9/8/2021
#
# evupdate utility script
########################################################################
dirname=`dirname $0`
basename=`basename $0`
utilname='evupdate-cp'
matchname='evupdate-match'
skipname='evupdate-skip'

if [ "$dirname" == "" ]; then
match=$matchname
else # [ "$dirname" == "" ]; then
match=$dirname/$matchname
fi # [ "$dirname" == "" ]; then

if [ "$dirname" == "" ]; then
skip=$skipname
else # [ "$dirname" == "" ]; then
skip=$dirname/$skipname
fi # [ "$dirname" == "" ]; then

if [ "$dirname" == "" ]; then
utility=$utilname
else # [ "$dirname" == "" ]; then
utility=$dirname/$utilname
fi # [ "$dirname" == "" ]; then

if [ "$1" != "" ] && [ "$2" != "" ]; then
$utility -p -m"`$match`" -k"`$skip`" $1 $2 $3 $4 $5 $6 $7 $8 $9
else
echo $utilname utility script
echo usage $basename sourcedir targetdir
echo $utility -p -m'"`'$match'`"' -k'"`'$skip'`"' '$1' '$2' '$3' '$4' '$5' '$6' '$7' '$8' '$9'
fi
