#!/bin/bash
########################################################################
# Copyright (c) 1988-2021 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: evupdate-match
#
# Author: $author$
#   Date: 3/31/2021
#
########################################################################
echo '*.orig;*.sh;*.h;*.c;*.m;*.hh;*.cc;*.mm;*.hxx;*.cxx;*.hpp;*.cpp;*.l;*.y;*.skl;*.txt;*.t;*.xml;*.xsl;*.xslt;*.html;*.js;*.css;*.jpg;*.png;*.gif;*.bmp;*.ico;*.pro;*.pri;*.rc;Doxyfile;Makefile.*;Makedefines.*;Makerules.*;Makedirs.*;Makefile;Makedefines;Makerules;Makedirs;*.code-workspace;*.sln;*.vcproj;*.vsprops;*.vcxproj;*.props;*.filters;*.gz'