#!/bin/bash
########################################################################
# Copyright (c) 1988-2021 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: evupdate
#
# Author: $author$
#   Date: 3/31/2021, 9/8/2021
#
# evls update utility script
########################################################################
dirname=`dirname $0`
basename=`basename $0`
utilname='evls'
cpname='evcp -d1'

if [ "$dirname" == "" ]; then
utility=$utilname
else # [ "$dirname" == "" ]; then
utility=$dirname/$utilname
fi # [ "$dirname" == "" ]; then

if [ "$1" != "" ] && [ "$2" != "" ]; then
$utility -d1 -r -f -b"$cpname \"" -w"\" \"" -a"\"" $1 $2 $3 $4 $5 $6 $7 $8 $9
else
echo $utilname update utility script
echo usage $basename sourcedir [targetdir] ...
echo $utility -d1 -r -f -b'"'$cpname '\''"''"' -w'"''\''"' '\''"''"' -a'"''\''"''"' 'sourcedir' 'targetdir' '$3' '$4' '$5' '$6' '$7' '$8' '$9'
fi
