#!/bin/bash
########################################################################
# Copyright (c) 1988-2021 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: upit
#
# Author: $author$
#   Date: 8/25/2021, 9/8/2021
#
# evup utility script
########################################################################
dirname=`dirname $0`
basename=`basename $0`
utilname='evup-diff'

if [ "$dirname" == "" ]; then
utility=$utilname
else # [ "$dirname" == "" ]; then
utility=$dirname/$utilname
fi # [ "$dirname" == "" ]; then

if [ "$1" != "" ] && [ "$2" != "" ]; then
  if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
  $utility -u $4 $5 $6 $1/$2/$3 $3 > update.sh
  else # [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]
  $utility -u $1/$2 $2 > update.sh
  fi # [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]
else # if [ "$1" != "" ] && [ "$2" != "" ]
 echo usage $basename '[tardir]' host directory
 echo $utility -u [tardir/]host/directory directory '>' update.sh
fi # if [ "$1" != "" ] && [ "$2" != "" ]
