///////////////////////////////////////////////////////////////////////
/// Copyright (c) 1988-2016 $organization$
///
/// This software is provided by the author and contributors ``as is'' 
/// and any express or implied warranties, including, but not limited to, 
/// the implied warranties of merchantability and fitness for a particular 
/// purpose are disclaimed. In no event shall the author or contributors 
/// be liable for any direct, indirect, incidental, special, exemplary, 
/// or consequential damages (including, but not limited to, procurement 
/// of substitute goods or services; loss of use, data, or profits; or 
/// business interruption) however caused and on any theory of liability, 
/// whether in contract, strict liability, or tort (including negligence 
/// or otherwise) arising in any way out of the use of this software, 
/// even if advised of the possibility of such damage.
///
///   File: main_opt.hpp
///
/// Author: $author$
///   Date: 1/6/2016
///////////////////////////////////////////////////////////////////////
#ifndef _TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_OPT_HPP
#define _TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_OPT_HPP

#include "talas/console/main.hpp"
#include "coral/console/daemon/main.hpp"

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPT "host"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTARG_REQUIRED XOS_MAIN_OPT_ARGUMENT_REQUIRED
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTARG_RESULT 0
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTARG "{xx.xx.xx.xx | name}"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTUSE "Tcp host address or name"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTVAL_S "h:"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTVAL_C 'h'
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTION \
   {TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTARG_REQUIRED, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTARG_RESULT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTVAL_C}, \

#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPT "port"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTARG_REQUIRED XOS_MAIN_OPT_ARGUMENT_REQUIRED
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTARG_RESULT 0
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTARG "number"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTUSE "Tcp port number"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTVAL_S "p:"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTVAL_C 'p'
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTION \
   {TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTARG_REQUIRED, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTARG_RESULT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTVAL_C}, \

#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPT "cert-file"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTARG_REQUIRED XOS_MAIN_OPT_ARGUMENT_REQUIRED
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTARG_RESULT 0
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTARG "filename"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTUSE "Server certificate file"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTVAL_S "c:"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTVAL_C 'c'
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTION \
   {TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTARG_REQUIRED, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTARG_RESULT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTVAL_C}, \

#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPT "key-file"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTARG_REQUIRED XOS_MAIN_OPT_ARGUMENT_REQUIRED
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTARG_RESULT 0
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTARG "filename"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTUSE "Server key file"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTVAL_S "k:"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTVAL_C 'k'
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTION \
   {TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTARG_REQUIRED, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTARG_RESULT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTVAL_C}, \

#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPT "trust-cert-file"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTARG_REQUIRED XOS_MAIN_OPT_ARGUMENT_REQUIRED
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTARG_RESULT 0
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTARG "filename"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTUSE "Trusted certificate(s) file"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTVAL_S "t:"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTVAL_C 't'
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTION \
   {TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTARG_REQUIRED, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTARG_RESULT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTVAL_C}, \

#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPT "trust-cert-directory"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTARG_REQUIRED XOS_MAIN_OPT_ARGUMENT_REQUIRED
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTARG_RESULT 0
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTARG "directory"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTUSE "Trusted certificate(s) directory"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTVAL_S "T:"
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTVAL_C 'T'
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTION \
   {TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTARG_REQUIRED, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTARG_RESULT, \
    TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTVAL_C}, \

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_OPTIONS_CHARS \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTVAL_S \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTVAL_S \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTVAL_S \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTVAL_S \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTVAL_S \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTVAL_S \
   CORAL_CONSOLE_DAEMON_MAIN_OPTIONS_CHARS

#define TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_OPTIONS_OPTIONS \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_HOST_OPTION \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_PORT_OPTION \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_CERT_FILE_OPTION \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_KEY_FILE_OPTION \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_FILE_OPTION \
   TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_TRUST_CERT_DIRECTORY_OPTION \
   CORAL_CONSOLE_DAEMON_MAIN_OPTIONS_OPTIONS

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////

namespace talas {
namespace protocol {
namespace tls {
namespace openssl {
namespace daemon {

} // namespace daemon 
} // namespace openssl 
} // namespace tls 
} // namespace protocol 
} // namespace talas 

#endif // _TALAS_PROTOCOL_TLS_OPENSSL_DAEMON_MAIN_OPT_HPP
