///////////////////////////////////////////////////////////////////////
//   File: evtlsatert.hpp
//
// Author: $author$
//   Date: 12/8/2007
///////////////////////////////////////////////////////////////////////

#ifndef _EVTLSATERT_HPP
#define _EVTLSATERT_HPP

///////////////////////////////////////////////////////////////////////
//   Enum:  
//
// Author: $author$
//   Date: 12/8/2007
///////////////////////////////////////////////////////////////////////
enum 
{
    TLS_ALERT_LEVEL_NONE = 0,
    TLS_ALERT_LEVEL_WARNING = 1,
    TLS_ALERT_LEVEL_FATAL = 2
};

#define TLS_ALERT_LEVEL_NAME_NONE "NONE"
#define TLS_ALERT_LEVEL_NAME_WARNING "WARNING"
#define TLS_ALERT_LEVEL_NAME_FATAL "FATAL"

///////////////////////////////////////////////////////////////////////
//   Enum:  
//
// Author: $author$
//   Date: 12/8/2007
///////////////////////////////////////////////////////////////////////
enum 
{
    TLS_ALERT_DESCRIPTION_CLOSE_NOTIFY = 0,
    TLS_ALERT_DESCRIPTION_UNEXPECTED_MESSAGE = 10,
    TLS_ALERT_DESCRIPTION_BAD_RECORD_MAC = 20,
    TLS_ALERT_DESCRIPTION_DECRYPTION_FAILED = 21,
    TLS_ALERT_DESCRIPTION_RECORD_OVERFLOW = 22,
    TLS_ALERT_DESCRIPTION_DECOMPRESSION_FAILURE = 30,
    TLS_ALERT_DESCRIPTION_HANDSHAKE_FAILURE = 40,
    TLS_ALERT_DESCRIPTION_BAD_CERTIFICATE = 42,
    TLS_ALERT_DESCRIPTION_UNSUPPORTED_CERTIFICATE = 43,
    TLS_ALERT_DESCRIPTION_CERTIFICATE_REVOKED = 44,
    TLS_ALERT_DESCRIPTION_CERTIFICATE_EXPIRED = 45,
    TLS_ALERT_DESCRIPTION_CERTIFICATE_UNKNOWN = 46,
    TLS_ALERT_DESCRIPTION_ILLEGAL_PARAMETER = 47,
    TLS_ALERT_DESCRIPTION_UNKNOWN_CA = 48,
    TLS_ALERT_DESCRIPTION_ACCESS_DENIED = 49,
    TLS_ALERT_DESCRIPTION_DECODE_ERROR = 50,
    TLS_ALERT_DESCRIPTION_DECRYPT_ERROR = 51,
    TLS_ALERT_DESCRIPTION_EXPORT_RESTRICTION = 60,
    TLS_ALERT_DESCRIPTION_PROTOCOL_VERSION = 70,
    TLS_ALERT_DESCRIPTION_INSUFFICIENT_SECURITY = 71,
    TLS_ALERT_DESCRIPTION_INTERNAL_ERROR = 80,
    TLS_ALERT_DESCRIPTION_USER_CANCELED = 90,
    TLS_ALERT_DESCRIPTION_NO_RENEGOTIATION = 100
};

#define TLS_ALERT_DESCRIPTION_NAME_CLOSE_NOTIFY "CLOSE_NOTIFY"
#define TLS_ALERT_DESCRIPTION_NAME_UNEXPECTED_MESSAGE "UNEXPECTED_MESSAGE"
#define TLS_ALERT_DESCRIPTION_NAME_BAD_RECORD_MAC "BAD_RECORD_MAC"
#define TLS_ALERT_DESCRIPTION_NAME_DECRYPTION_FAILED "DECRYPTION_FAILED"
#define TLS_ALERT_DESCRIPTION_NAME_RECORD_OVERFLOW "RECORD_OVERFLOW"
#define TLS_ALERT_DESCRIPTION_NAME_DECOMPRESSION_FAILURE "DECOMPRESSION_FAILURE"
#define TLS_ALERT_DESCRIPTION_NAME_HANDSHAKE_FAILURE "HANDSHAKE_FAILURE"
#define TLS_ALERT_DESCRIPTION_NAME_BAD_CERTIFICATE "BAD_CERTIFICATE"
#define TLS_ALERT_DESCRIPTION_NAME_UNSUPPORTED_CERTIFICATE "UNSUPPORTED_CERTIFICATE"
#define TLS_ALERT_DESCRIPTION_NAME_CERTIFICATE_REVOKED "CERTIFICATE_REVOKED"
#define TLS_ALERT_DESCRIPTION_NAME_CERTIFICATE_EXPIRED "CERTIFICATE_EXPIRED"
#define TLS_ALERT_DESCRIPTION_NAME_CERTIFICATE_UNKNOWN "CERTIFICATE_UNKNOWN"
#define TLS_ALERT_DESCRIPTION_NAME_ILLEGAL_PARAMETER "ILLEGAL_PARAMETER"
#define TLS_ALERT_DESCRIPTION_NAME_UNKNOWN_CA "UNKNOWN_CA"
#define TLS_ALERT_DESCRIPTION_NAME_ACCESS_DENIED "ACCESS_DENIED"
#define TLS_ALERT_DESCRIPTION_NAME_DECODE_ERROR "DECODE_ERROR"
#define TLS_ALERT_DESCRIPTION_NAME_DECRYPT_ERROR "DECRYPT_ERROR"
#define TLS_ALERT_DESCRIPTION_NAME_EXPORT_RESTRICTION "EXPORT_RESTRICTION"
#define TLS_ALERT_DESCRIPTION_NAME_PROTOCOL_VERSION "PROTOCOL_VERSION"
#define TLS_ALERT_DESCRIPTION_NAME_INSUFFICIENT_SECURITY "INSUFFICIENT_SECURITY"
#define TLS_ALERT_DESCRIPTION_NAME_INTERNAL_ERROR "INTERNAL_ERROR"
#define TLS_ALERT_DESCRIPTION_NAME_USER_CANCELED "USER_CANCELED"
#define TLS_ALERT_DESCRIPTION_NAME_NO_RENEGOTIATION "NO_RENEGOTIATION"

#endif // _EVTLSATERT_HPP
