///////////////////////////////////////////////////////////////////////
/// Copyright (c) 1988-2014 $organization$
///
/// This software is provided by the author and contributors ``as is'' 
/// and any express or implied warranties, including, but not limited to, 
/// the implied warranties of merchantability and fitness for a particular 
/// purpose are disclaimed. In no event shall the author or contributors 
/// be liable for any direct, indirect, incidental, special, exemplary, 
/// or consequential damages (including, but not limited to, procurement 
/// of substitute goods or services; loss of use, data, or profits; or 
/// business interruption) however caused and on any theory of liability, 
/// whether in contract, strict liability, or tort (including negligence 
/// or otherwise) arising in any way out of the use of this software, 
/// even if advised of the possibility of such damage.
///
///   File: main_opt.hpp
///
/// Author: $author$
///   Date: 12/17/2014
///////////////////////////////////////////////////////////////////////
#ifndef _CORAL_APP_CONSOLE_CORAL_MAIN_OPT_HPP
#define _CORAL_APP_CONSOLE_CORAL_MAIN_OPT_HPP

#include "coral/console/main.hpp"

#define CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG_FILE "<filename>"
#define CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG_STDIO "(-)<stdio>"
#define CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG "{" \
    CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG_FILE " | " \
    CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG_STDIO "}" \

#define CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPT "argv"
#define CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTARG_RESULT 0
#define CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTARG CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG
#define CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTUSE "Argv source"
#define CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTVAL_S "a:"
#define CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTVAL_C 'a'
#define CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTION \
   {CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTARG_REQUIRED, \
    CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTARG_RESULT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTVAL_C}, \

#define CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPT "env"
#define CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTARG_RESULT 0
#define CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTARG CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG
#define CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTUSE "Env source"
#define CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTVAL_S "e:"
#define CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTVAL_C 'e'
#define CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTION \
   {CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTARG_REQUIRED, \
    CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTARG_RESULT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTVAL_C}, \

#define CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPT "input"
#define CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTARG_RESULT 0
#define CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTARG CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG
#define CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTUSE "Input source"
#define CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTVAL_S "i:"
#define CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTVAL_C 'i'
#define CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTION \
   {CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTARG_REQUIRED, \
    CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTARG_RESULT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTVAL_C}, \

#define CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPT "output"
#define CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTARG_RESULT 0
#define CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTARG CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG
#define CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTUSE "Output target"
#define CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTVAL_S "o:"
#define CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTVAL_C 'o'
#define CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTION \
   {CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTARG_REQUIRED, \
    CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTARG_RESULT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTVAL_C}, \

#define CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPT "stdin"
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTARG_RESULT 0
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTARG CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTUSE "Stdin source"
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTVAL_S "I:"
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTVAL_C 'I'
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTION \
   {CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTARG_REQUIRED, \
    CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTARG_RESULT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTVAL_C}, \

#define CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPT "stdout"
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTARG_RESULT 0
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTARG CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTUSE "Stdout target"
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTVAL_S "O:"
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTVAL_C 'O'
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTION \
   {CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTARG_REQUIRED, \
    CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTARG_RESULT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTVAL_C}, \

#define CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPT "stderr"
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTARG_RESULT 0
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTARG CORAL_APP_CONSOLE_CORAL_MAIN_PATH_OPTARG
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTUSE "Stderr target"
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTVAL_S "E:"
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTVAL_C 'E'
#define CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTION \
   {CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTARG_REQUIRED, \
    CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTARG_RESULT, \
    CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTVAL_C}, \

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
#define CORAL_APP_CONSOLE_CORAL_MAIN_OPTIONS_CHARS \
   CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTVAL_S \
   CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTVAL_S \
   CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTVAL_S \
   CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTVAL_S \
   CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTVAL_S \
   CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTVAL_S \
   CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTVAL_S \
   CORAL_CONSOLE_MAIN_OPTIONS_CHARS

#define CORAL_APP_CONSOLE_CORAL_MAIN_OPTIONS_OPTIONS \
   CORAL_APP_CONSOLE_CORAL_MAIN_ARGV_OPTION \
   CORAL_APP_CONSOLE_CORAL_MAIN_ENV_OPTION \
   CORAL_APP_CONSOLE_CORAL_MAIN_INPUT_OPTION \
   CORAL_APP_CONSOLE_CORAL_MAIN_OUTPUT_OPTION \
   CORAL_APP_CONSOLE_CORAL_MAIN_STDIN_OPTION \
   CORAL_APP_CONSOLE_CORAL_MAIN_STDOUT_OPTION \
   CORAL_APP_CONSOLE_CORAL_MAIN_STDERR_OPTION \
   CORAL_CONSOLE_MAIN_OPTIONS_OPTIONS

namespace coral {
namespace app {
namespace console {
namespace coral {

} // namespace coral 
} // namespace console 
} // namespace app 
} // namespace coral 

#endif // _CORAL_APP_CONSOLE_CORAL_MAIN_OPT_HPP 
