///////////////////////////////////////////////////////////////////////
/// Copyright (c) 1988-2014 $organization$
///
/// This software is provided by the author and contributors ``as is'' 
/// and any express or implied warranties, including, but not limited to, 
/// the implied warranties of merchantability and fitness for a particular 
/// purpose are disclaimed. In no event shall the author or contributors 
/// be liable for any direct, indirect, incidental, special, exemplary, 
/// or consequential damages (including, but not limited to, procurement 
/// of substitute goods or services; loss of use, data, or profits; or 
/// business interruption) however caused and on any theory of liability, 
/// whether in contract, strict liability, or tort (including negligence 
/// or otherwise) arising in any way out of the use of this software, 
/// even if advised of the possibility of such damage.
///
///   File: main_opt.hpp
///
/// Author: $author$
///   Date: 12/3/2014
///////////////////////////////////////////////////////////////////////
#ifndef _XOS_NADIR_XOS_APP_CONSOLE_HELLO_MAIN_OPT_HPP
#define _XOS_NADIR_XOS_APP_CONSOLE_HELLO_MAIN_OPT_HPP

#include "xos/base/getopt/main.hpp"

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPT "message"
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTARG "<string>"
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTUSE "Message literal"
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTVAL_S "m:"
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTVAL_C 'm'
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTION \
   {XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPT, \
    XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTARG_RESULT, \
    XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTVAL_C}, \

#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPT "message-file"
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTARG "<filename>"
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTUSE "Message file"
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTVAL_S "M:"
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTVAL_C 'M'
#define XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTION \
   {XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPT, \
    XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTARG_RESULT, \
    XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTVAL_C}, \

#define XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPT "input"
#define XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_NONE
#define XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTARG ""
#define XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTUSE "Use message input or file"
#define XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTVAL_S "i"
#define XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTVAL_C 'i'
#define XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTION \
   {XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPT, \
    XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTARG_RESULT, \
    XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTVAL_C}, \

#define XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPT "client"
#define XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_NONE
#define XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTARG ""
#define XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTUSE "Run as client"
#define XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTVAL_S "c"
#define XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTVAL_C 'c'
#define XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTION \
   {XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPT, \
    XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTARG_RESULT, \
    XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTVAL_C}, \

#define XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPT "server"
#define XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_NONE
#define XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTARG ""
#define XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTUSE "Run as server"
#define XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTVAL_S "s"
#define XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTVAL_C 's'
#define XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTION \
   {XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPT, \
    XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTARG_RESULT, \
    XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTVAL_C}, \

#define XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPT "host"
#define XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTARG "{name | ddd.ddd.ddd.ddd | *}"
#define XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTUSE "Host name, address or any"
#define XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTVAL_S "h:"
#define XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTVAL_C 'h'
#define XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTION \
   {XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPT, \
    XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTARG_RESULT, \
    XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTVAL_C}, \

#define XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPT "port"
#define XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTARG "{0..2^16-1}"
#define XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTUSE "Port number"
#define XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTVAL_S "p:"
#define XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTVAL_C 'p'
#define XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTION \
   {XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPT, \
    XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTARG_RESULT, \
    XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTVAL_C}, \

#define XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPT "family"
#define XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTARG_IPV4 "(4)ipv4"
#define XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTARG_IPV6 "(6)ipv6"
#define XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTARG_LOCAL "(l)local"
#define XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTARG \
    "{" XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTARG_IPV4 \
    " | " XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTARG_IPV6 \
    " | " XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTARG_LOCAL "}"
#define XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTUSE "Address family"
#define XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTVAL_S "f:"
#define XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTVAL_C 'f'
#define XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTION \
   {XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPT, \
    XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTARG_RESULT, \
    XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTVAL_C}, \

#define XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPT "transport"
#define XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTARG_TCP "(t)tcp"
#define XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTARG_UDP "(u)udp"
#define XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTARG \
    "{" XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTARG_TCP \
    " | " XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTARG_UDP "}"
#define XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTUSE ""
#define XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTVAL_S "t:"
#define XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTVAL_C 't'
#define XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTION \
   {XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPT, \
    XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTARG_RESULT, \
    XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTVAL_C}, \

#define XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPT "logging"
#define XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_REQUIRED
#define XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTARG XOS_MAIN_LOGGING_OPTARG
#define XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTUSE XOS_MAIN_LOGGING_OPTUSE
#define XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTVAL_S "l:"
#define XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTVAL_C 'l'
#define XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTION \
   {XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPT, \
    XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTARG_RESULT, \
    XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTVAL_C}, \

#define XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPT "usage"
#define XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTARG_REQUIRED MAIN_OPT_ARGUMENT_NONE
#define XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTARG_RESULT 0
#define XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTARG XOS_MAIN_HELP_OPTARG
#define XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTUSE XOS_MAIN_HELP_OPTUSE
#define XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTVAL_S "u"
#define XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTVAL_C 'u'
#define XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTION \
   {XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPT, \
    XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTARG_REQUIRED, \
    XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTARG_RESULT, \
    XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTVAL_C}, \

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
#define XOS_APP_CONSOLE_HELLO_MAIN_OPTIONS_CHARS \
   XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTVAL_S \
   XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTVAL_S \
   XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTVAL_S \
   XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTVAL_S \
   XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTVAL_S \
   XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTVAL_S \
   XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTVAL_S \
   XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTVAL_S \
   XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTVAL_S \
   XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTVAL_S \
   XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTVAL_S

#define XOS_APP_CONSOLE_HELLO_MAIN_OPTIONS_OPTIONS \
   XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_OPTION \
   XOS_APP_CONSOLE_HELLO_MAIN_MESSAGE_FILE_OPTION \
   XOS_APP_CONSOLE_HELLO_MAIN_INPUT_OPTION \
   XOS_APP_CONSOLE_HELLO_MAIN_CLIENT_OPTION \
   XOS_APP_CONSOLE_HELLO_MAIN_SERVER_OPTION \
   XOS_APP_CONSOLE_HELLO_MAIN_HOST_OPTION \
   XOS_APP_CONSOLE_HELLO_MAIN_PORT_OPTION \
   XOS_APP_CONSOLE_HELLO_MAIN_FAMILY_OPTION \
   XOS_APP_CONSOLE_HELLO_MAIN_TRANSPORT_OPTION \
   XOS_APP_CONSOLE_HELLO_MAIN_LOGGING_OPTION \
   XOS_APP_CONSOLE_HELLO_MAIN_USAGE_OPTION

namespace xos {
namespace app {
namespace console {
namespace hello {

} // namespace hello 
} // namespace console 
} // namespace app 
} // namespace xos 

#endif // _XOS_NADIR_XOS_APP_CONSOLE_HELLO_MAIN_OPT_HPP 
